# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_GameConfigWidget.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GameConfigWidget(object):
    def setupUi(self, GameConfigWidget):
        GameConfigWidget.setObjectName("GameConfigWidget")
        GameConfigWidget.resize(846, 663)
        self.main_layout = QtWidgets.QHBoxLayout(GameConfigWidget)
        self.main_layout.setObjectName("main_layout")
        self.widget = QtWidgets.QWidget(GameConfigWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMaximumSize(QtCore.QSize(400, 16777215))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_4 = QtWidgets.QWidget(self.groupBox)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.game_combobox = QtWidgets.QComboBox(self.widget_4)
        self.game_combobox.setObjectName("game_combobox")
        self.horizontalLayout_4.addWidget(self.game_combobox)
        self.resolution_combobox = QtWidgets.QComboBox(self.widget_4)
        self.resolution_combobox.setObjectName("resolution_combobox")
        self.horizontalLayout_4.addWidget(self.resolution_combobox)
        self.load_button = QtWidgets.QPushButton(self.widget_4)
        self.load_button.setObjectName("load_button")
        self.horizontalLayout_4.addWidget(self.load_button)
        self.verticalLayout_4.addWidget(self.widget_4)
        self.widget_5 = QtWidgets.QWidget(self.groupBox)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.widget_5)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_2.addWidget(self.buttonBox)
        self.verticalLayout_4.addWidget(self.widget_5)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.state_listWidget = QtWidgets.QListWidget(self.groupBox_2)
        self.state_listWidget.setObjectName("state_listWidget")
        self.horizontalLayout.addWidget(self.state_listWidget)
        self.widget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.state_add_toolButton = QtWidgets.QToolButton(self.widget_2)
        self.state_add_toolButton.setObjectName("state_add_toolButton")
        self.verticalLayout_2.addWidget(self.state_add_toolButton)
        self.state_remove_toolButton = QtWidgets.QToolButton(self.widget_2)
        self.state_remove_toolButton.setObjectName("state_remove_toolButton")
        self.verticalLayout_2.addWidget(self.state_remove_toolButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.widget_2)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.action_listWidget = QtWidgets.QListWidget(self.groupBox_3)
        self.action_listWidget.setObjectName("action_listWidget")
        self.horizontalLayout_3.addWidget(self.action_listWidget)
        self.widget_3 = QtWidgets.QWidget(self.groupBox_3)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.action_add_toolButton = QtWidgets.QToolButton(self.widget_3)
        self.action_add_toolButton.setObjectName("action_add_toolButton")
        self.verticalLayout_3.addWidget(self.action_add_toolButton)
        self.action_remove_toolButton = QtWidgets.QToolButton(self.widget_3)
        self.action_remove_toolButton.setObjectName("action_remove_toolButton")
        self.verticalLayout_3.addWidget(self.action_remove_toolButton)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.horizontalLayout_3.addWidget(self.widget_3)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.main_layout.addWidget(self.widget)
        self.placeholder_label = QtWidgets.QLabel(GameConfigWidget)
        self.placeholder_label.setAlignment(QtCore.Qt.AlignCenter)
        self.placeholder_label.setObjectName("placeholder_label")
        self.main_layout.addWidget(self.placeholder_label)

        self.retranslateUi(GameConfigWidget)
        QtCore.QMetaObject.connectSlotsByName(GameConfigWidget)

    def retranslateUi(self, GameConfigWidget):
        _translate = QtCore.QCoreApplication.translate
        GameConfigWidget.setWindowTitle(_translate("GameConfigWidget", "Form"))
        self.groupBox.setTitle(_translate("GameConfigWidget", "Game"))
        self.load_button.setText(_translate("GameConfigWidget", "Load"))
        self.groupBox_2.setTitle(_translate("GameConfigWidget", "Game States"))
        self.state_add_toolButton.setText(_translate("GameConfigWidget", "+"))
        self.state_remove_toolButton.setText(_translate("GameConfigWidget", "-"))
        self.groupBox_3.setTitle(_translate("GameConfigWidget", "Game Actions"))
        self.action_add_toolButton.setText(_translate("GameConfigWidget", "+"))
        self.action_remove_toolButton.setText(_translate("GameConfigWidget", "-"))
        self.placeholder_label.setText(_translate("GameConfigWidget", "Choose one"))
