# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_StatusWidget.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StatusWidget(object):
    def setupUi(self, StatusWidget):
        StatusWidget.setObjectName("StatusWidget")
        StatusWidget.resize(1144, 871)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        StatusWidget.setFont(font)
        StatusWidget.setStyleSheet("")
        self.horizontalLayout = QtWidgets.QHBoxLayout(StatusWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(StatusWidget)
        self.groupBox.setStyleSheet("QGroupBox#groupbox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 9px;\n"
"    margin-top: 0.5em;\n"
"}")
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.game_groupbox = QtWidgets.QGroupBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.game_groupbox.setFont(font)
        self.game_groupbox.setObjectName("game_groupbox")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.game_groupbox)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.widget_3 = QtWidgets.QWidget(self.game_groupbox)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(2)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.groupBox_5 = QtWidgets.QGroupBox(self.widget_3)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.game_combobox = QtWidgets.QComboBox(self.groupBox_5)
        self.game_combobox.setMinimumSize(QtCore.QSize(0, 0))
        self.game_combobox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.game_combobox.setObjectName("game_combobox")
        self.horizontalLayout_4.addWidget(self.game_combobox)
        self.horizontalLayout_7.addWidget(self.groupBox_5)
        self.groupBox_4 = QtWidgets.QGroupBox(self.widget_3)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.resolution_combobox = QtWidgets.QComboBox(self.groupBox_4)
        self.resolution_combobox.setMinimumSize(QtCore.QSize(0, 0))
        self.resolution_combobox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.resolution_combobox.setObjectName("resolution_combobox")
        self.horizontalLayout_5.addWidget(self.resolution_combobox)
        self.horizontalLayout_7.addWidget(self.groupBox_4)
        self.verticalLayout_9.addWidget(self.widget_3)
        self.groupBox_6 = QtWidgets.QGroupBox(self.game_groupbox)
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.window_chosen_combo_box = QtWidgets.QComboBox(self.groupBox_6)
        self.window_chosen_combo_box.setMinimumSize(QtCore.QSize(0, 0))
        self.window_chosen_combo_box.setMaximumSize(QtCore.QSize(350, 16777215))
        self.window_chosen_combo_box.setObjectName("window_chosen_combo_box")
        self.horizontalLayout_3.addWidget(self.window_chosen_combo_box)
        self.window_chosen_refresh_button = QtWidgets.QToolButton(self.groupBox_6)
        self.window_chosen_refresh_button.setMinimumSize(QtCore.QSize(0, 0))
        self.window_chosen_refresh_button.setObjectName("window_chosen_refresh_button")
        self.horizontalLayout_3.addWidget(self.window_chosen_refresh_button)
        self.verticalLayout_9.addWidget(self.groupBox_6)
        self.verticalLayout_2.addWidget(self.game_groupbox)
        self.widget_2 = QtWidgets.QWidget(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.widget_2.setFont(font)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.status_groupbox = QtWidgets.QGroupBox(self.widget_2)
        self.status_groupbox.setObjectName("status_groupbox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.status_groupbox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_10 = QtWidgets.QGroupBox(self.status_groupbox)
        self.groupBox_10.setTitle("")
        self.groupBox_10.setObjectName("groupBox_10")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_10)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label = QtWidgets.QLabel(self.groupBox_10)
        self.label.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        self.from_combobox = QtWidgets.QComboBox(self.groupBox_10)
        self.from_combobox.setMinimumSize(QtCore.QSize(0, 0))
        self.from_combobox.setObjectName("from_combobox")
        self.horizontalLayout_6.addWidget(self.from_combobox)
        self.verticalLayout_4.addWidget(self.groupBox_10)
        self.groupBox_11 = QtWidgets.QGroupBox(self.status_groupbox)
        self.groupBox_11.setTitle("")
        self.groupBox_11.setObjectName("groupBox_11")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.groupBox_11)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_3 = QtWidgets.QLabel(self.groupBox_11)
        self.label_3.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_8.addWidget(self.label_3)
        self.to_combobox = QtWidgets.QComboBox(self.groupBox_11)
        self.to_combobox.setMinimumSize(QtCore.QSize(0, 0))
        self.to_combobox.setObjectName("to_combobox")
        self.horizontalLayout_8.addWidget(self.to_combobox)
        self.verticalLayout_4.addWidget(self.groupBox_11)
        self.groupBox_12 = QtWidgets.QGroupBox(self.status_groupbox)
        self.groupBox_12.setTitle("")
        self.groupBox_12.setObjectName("groupBox_12")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.groupBox_12)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_2 = QtWidgets.QLabel(self.groupBox_12)
        self.label_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_9.addWidget(self.label_2)
        self.must_combobox = QtWidgets.QComboBox(self.groupBox_12)
        self.must_combobox.setMinimumSize(QtCore.QSize(0, 0))
        self.must_combobox.setObjectName("must_combobox")
        self.horizontalLayout_9.addWidget(self.must_combobox)
        self.verticalLayout_4.addWidget(self.groupBox_12)
        self.verticalLayout.addWidget(self.status_groupbox)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.start_button = QtWidgets.QPushButton(self.groupBox)
        self.start_button.setObjectName("start_button")
        self.verticalLayout_2.addWidget(self.start_button)
        self.stop_button = QtWidgets.QPushButton(self.groupBox)
        self.stop_button.setObjectName("stop_button")
        self.verticalLayout_2.addWidget(self.stop_button)
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBox_7 = QtWidgets.QGroupBox(StatusWidget)
        self.groupBox_7.setStyleSheet("#groupbox_7 {\n"
"border-width: 1px;\n"
"border-color: rgb(99, 99, 99);\n"
"border-style: solid;\n"
"}")
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.screen_label = QtWidgets.QLabel(self.groupBox_8)
        self.screen_label.setMinimumSize(QtCore.QSize(800, 450))
        self.screen_label.setMaximumSize(QtCore.QSize(800, 450))
        self.screen_label.setObjectName("screen_label")
        self.verticalLayout_3.addWidget(self.screen_label)
        self.verticalLayout_10.addWidget(self.groupBox_8)
        self.widget = QtWidgets.QWidget(self.groupBox_7)
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox_9 = QtWidgets.QGroupBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_9.setFont(font)
        self.groupBox_9.setObjectName("groupBox_9")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.prev_screen_label = QtWidgets.QLabel(self.groupBox_9)
        self.prev_screen_label.setMinimumSize(QtCore.QSize(480, 270))
        self.prev_screen_label.setMaximumSize(QtCore.QSize(480, 270))
        self.prev_screen_label.setObjectName("prev_screen_label")
        self.verticalLayout_5.addWidget(self.prev_screen_label)
        self.horizontalLayout_2.addWidget(self.groupBox_9)
        self.status_table = QtWidgets.QTableWidget(self.widget)
        self.status_table.setObjectName("status_table")
        self.status_table.setColumnCount(0)
        self.status_table.setRowCount(0)
        self.horizontalLayout_2.addWidget(self.status_table)
        self.verticalLayout_10.addWidget(self.widget)
        self.horizontalLayout.addWidget(self.groupBox_7)

        self.retranslateUi(StatusWidget)
        QtCore.QMetaObject.connectSlotsByName(StatusWidget)

    def retranslateUi(self, StatusWidget):
        _translate = QtCore.QCoreApplication.translate
        StatusWidget.setWindowTitle(_translate("StatusWidget", "Form"))
        self.groupBox.setTitle(_translate("StatusWidget", "Run configuration"))
        self.game_groupbox.setTitle(_translate("StatusWidget", "Game Settings"))
        self.groupBox_5.setTitle(_translate("StatusWidget", "Game Name"))
        self.groupBox_4.setTitle(_translate("StatusWidget", "Window Resolution"))
        self.groupBox_6.setTitle(_translate("StatusWidget", "Game Window"))
        self.window_chosen_refresh_button.setText(_translate("StatusWidget", "R"))
        self.status_groupbox.setTitle(_translate("StatusWidget", "Executing Path"))
        self.label.setText(_translate("StatusWidget", "From"))
        self.label_3.setText(_translate("StatusWidget", "To"))
        self.label_2.setText(_translate("StatusWidget", "Must"))
        self.start_button.setText(_translate("StatusWidget", "Start"))
        self.stop_button.setText(_translate("StatusWidget", "Stop"))
        self.groupBox_7.setTitle(_translate("StatusWidget", "Run-time Dashboard"))
        self.groupBox_8.setTitle(_translate("StatusWidget", "Current Screenshot"))
        self.screen_label.setText(_translate("StatusWidget", "Waiting for screenshot..."))
        self.groupBox_9.setTitle(_translate("StatusWidget", "Previous Screenshot"))
        self.prev_screen_label.setText(_translate("StatusWidget", "Waiting for screenshot..."))
